use fork instead of owner when creating blob
gr2m/octokit-plugin-create-pull-request pull request #82
Opened 2022-02-09 17:00 UTC by pelikhan

When creating a commit with binary files (e.g. images) on a fork, we incorrectly try to create the tree in the original repo.

2022-02-09 17:39 UTC, pelikhan commented
Tested as working on jacdac.

2022-03-03 18:56 UTC, gr2m requested changes
Thank you for the pull request Peli! Could you please add a test that fails without your changes, so we make sure this won't break again in future?

2022-03-03 19:43 UTC, pelikhan commented
I tried following the docs in contributing but it is unclear where the my-script.js should be dropped. I tried to run a build, then pkg/dist-node but that did not work out.

2022-03-03 19:47 UTC, gr2m commented
I feel like the problem should be covered in this existing test:
https://github.com/gr2m/octokit-plugin-create-pull-request/blob/main/test/use-fork.test.ts

Maybe you can update it to also include a blob?

2022-03-03 19:56 UTC, pelikhan commented
I could try to remix it with the blob test at https://github.com/gr2m/octokit-plugin-create-pull-request/blob/main/test/create-binary-file.test.ts#L51

2022-03-03 20:27 UTC, gr2m commented
either works

2022-03-03 22:44 UTC, pelikhan commented
Closed in favor of https://github.com/gr2m/octokit-plugin-create-pull-request/pull/84 because git.

2022-03-03 22:44 UTC, closed without merging

2022-03-04 00:45 UTC, anandchakru commented
The 404 got fixed, but now I'm starting to get the following error:

```
HttpError: base_tree is not a valid tree oid
    at fetch-wrapper.js:68:1
    at async createTree (create-tree.js:57:1)
    at async composeCreatePullRequest (compose-create-pull-request.js:56:1)
```

The createPullRequest is created by a non-contributor (not the owner/contributor of the repo), so github automatically creates a fork repo under this `non-contributor` and in that is causing the above error. 🤔

2022-03-04 00:48 UTC, gr2m commented
> Update: Might be [this](https://stackoverflow.com/a/45026785/234110), I will continue testing and keep you updated

Thank you!